NLP Model With Tfidf Vectorization !

    We create a NLP model and predict out the probabality of our model is good aur bad !

    We are going to perform *vectorization technique !

    Also doing multihotcoding !



In [1]:
import pandas as pd
import numpy as np

In [2]:
# Reading the data from csv file !

dataset = pd.read_csv('balanced_reviews.csv')

In [3]:
# Let's perform some investigation!

dataset.shape

(792000, 3)

In [4]:
dataset.columns.tolist()

['overall', 'reviewText', 'summary']

In [5]:
dataset.sample()

overall                                         reviewText    summary
449785        2  Cute warm outfit but design started coming off...  Two Stars

In [6]:
dataset.head()

overall                                         reviewText  \
0        5      Great nephew loved!!! Very fast delivery!!!!!   
1        5                     well made boot, fits perfectly   
2        5  Perfect fit. Good quality. (Do not put in dryer.)   
3        5  I bought these for my 2 year old girl and she ...   
4        5  Great backpack.  I wanted to get a backpack th...   

                   summary  
0               Five Stars  
1               Five Stars  
2                Nice bra!  
3  Better than I expected!  
4          Great backpack.

In [7]:
# View the 10 reviewtext !

dataset['reviewText'].sample(10)

733772    Toe box is not as wide as previous model. Mesh...
717175    This class is made in China. I think ray ban i...
627196    We got these at a reduced price and we're surp...
565829    I ordered a large and it was too short. It sti...
680693    This is a nice tee shirt but I feel ripped off...
683365    The picture depicted does not look like the ac...
322937    I love the wallet, it's thin and works great. ...
90851     Pretty cheap looking in appearance but you get...
287487    Too small doesnt fit anything false advertisin...
252948    I like these shoes but the toe straps drives m...
Name: reviewText, dtype: object

In [8]:
# Let's view the reviewText data for top 10 rows !

dataset['reviewText'].head(10)

0        Great nephew loved!!! Very fast delivery!!!!!
1                       well made boot, fits perfectly
2    Perfect fit. Good quality. (Do not put in dryer.)
3    I bought these for my 2 year old girl and she ...
4    Great backpack.  I wanted to get a backpack th...
5    I use these every day.  They smell great and w...
6                                           Nice pants
7    The first pair of jazz shoes my daughter didn'...
8    Got these shoes for my elderly mother. They fi...
9    I love the Keen Newport Sandal!, they are dura...
Name: reviewText, dtype: object

In [9]:
# In overall we have ratings let's know the counts for ratings 1-5 !

dataset['overall'].unique()

array([5, 4, 3, 2, 1], dtype=int64)

In [10]:
# Let's count how many reviews we have for 1 - 5 !

dataset['overall'].value_counts()

3    264000
5    132000
4    132000
2    132000
1    132000
Name: overall, dtype: int64

In [11]:
# Missing values !

dataset.isnull().any(axis = 0)

overall       False
reviewText     True
summary        True
dtype: bool

In [12]:
# Let's drop the columns where we have missing data !

dataset.dropna(inplace = True)

In [13]:
# again check the missing values !

dataset.isnull().any(axis = 0)

overall       False
reviewText    False
summary       False
dtype: bool

In [14]:
# Let's drop the data which have ratings - 3 !

dataset = dataset[dataset['overall'] != 3]

In [15]:
dataset['overall'].value_counts()

2    131939
1    131876
4    131849
5    131719
Name: overall, dtype: int64

Create a new columns !

    And divided the overall ratings in two categories !
    0 - negative ratings !
    1 - positive ratings !

In [16]:
dataset['Positivity'] = np.where(dataset['overall'] > 3 , 1 , 0)

In [17]:
dataset['Positivity'].value_counts()

0    263815
1    263568
Name: Positivity, dtype: int64

In [18]:
dataset['reviewText'].head(10)

0        Great nephew loved!!! Very fast delivery!!!!!
1                       well made boot, fits perfectly
2    Perfect fit. Good quality. (Do not put in dryer.)
3    I bought these for my 2 year old girl and she ...
4    Great backpack.  I wanted to get a backpack th...
5    I use these every day.  They smell great and w...
6                                           Nice pants
7    The first pair of jazz shoes my daughter didn'...
8    Got these shoes for my elderly mother. They fi...
9    I love the Keen Newport Sandal!, they are dura...
Name: reviewText, dtype: object

NLP Data we have to convert our freeform text data into numeric representation !

    To create a ML model all algorithms need data in numeric format. !



In [19]:
# Perform train_test_split

from sklearn.model_selection import train_test_split

In [20]:
# Separate out the features and labels !

features = dataset['reviewText']

labels = dataset['Positivity']

In [21]:
# Splitting the dataset into train and test !

features_train , features_test , labels_train , labels_test = train_test_split(features , labels , test_size = 0.4 ,
                                                                               random_state = 0)

Now we have to convert our NLP text data to a numeric representation using *Vectorization technique !

    We are going to use CountVectorizer !



In [22]:
# Import a class count

from sklearn.feature_extraction.text import CountVectorizer

In [23]:
# Create a object !

vect = CountVectorizer()

* Perform first activity to find out the Vocabulary / to create Vocabulary / to find out the list of unique words !

In [24]:
#step 1 - Give the data !

vect.fit(features_train)

CountVectorizer()

In [25]:
#step 2 - Convert text data into multihotcoding or bag of word . !
#transform !

features_train_vectorised = vect.transform(features_train)


    now -

features = features_train_vectorised

labels


In [26]:
# What is the count of unique words !

len(vect.get_feature_names())

58902

In [27]:
# let's print unique words !

vect.get_feature_names()[10000 : 10010] # - you can take any value like [11000 : 11010]

['btw',
 'btwn',
 'bu',
 'bu2010',
 'bub',
 'bubble',
 'bubbled',
 'bubblegum',
 'bubbles',
 'bubbleum']

Transform !

In [28]:
features_train_vectorised = vect.transform(features_train)

In [29]:
# check the shape of features_train_vectorised !

features_train_vectorised.shape

(316429, 58902)

In [30]:
# check the number of reviews !

len(features_train)

316429

Create the classifier (a model which can classifier our reviews whether it's a +ve(positive) review or -ve(nagative) review .

    Binary Classification need to use algorithms which can done classifications .

    Based on the observation Logisticregression gives the best result if we are dealing with NLP data. !



In [31]:
# Logistic Regression Model !

from sklearn.linear_model import LogisticRegression

In [32]:
# Create object of it !

model = LogisticRegression()

In [33]:
# Now fit the model !

model.fit(features_train_vectorised , labels_train)

C:\Users\Bad Boy\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [34]:
# Evaluate the Models !
# Model Testing !

prediction = model.predict(vect.transform(features_test))

Let's check our Model is Working Good aur Bad interms of Classification !

In [35]:
#import Confusion Matrix !

from sklearn.metrics import confusion_matrix

In [36]:
confusion_matrix(labels_test , prediction)

array([[94943, 10349],
       [10967, 94695]], dtype=int64)

In [37]:
# Let's Calculate rthe Accuracy of the Model !

from sklearn.metrics import accuracy_score

In [38]:
accuracy_score(labels_test , prediction)

0.8989542743915735

Check the Probability of our Model !

    Probability < 50 = 0 !
    Probability >= 50 = 1 !



In [39]:
prediction

array([1, 0, 0, ..., 1, 1, 1])

In [40]:
model.predict_proba(vect.transform(features_test))

array([[8.98746552e-05, 9.99910125e-01],
       [5.67817760e-01, 4.32182240e-01],
       [9.99999719e-01, 2.80588916e-07],
       ...,
       [1.09885512e-04, 9.99890114e-01],
       [2.31974828e-01, 7.68025172e-01],
       [2.76318326e-01, 7.23681674e-01]])

Prediction the Probability / Score of our model is - 89.89% !