NLP Model With Tfidf Vectorization !

    We create a NLP model and predict out the probabality of our model is good aur bad !

    We are going to perform *vectorization technique !

    Also doing multihotcoding !



In [1]:
import pandas as pd
import numpy as np

In [2]:
#Read the data from csv file !

dataset = pd.read_csv('balanced_reviews.csv')

In [3]:
#Let's do some investigation !

dataset.shape

(792000, 3)

In [4]:
dataset.columns.tolist()

['overall', 'reviewText', 'summary']

In [5]:
# view the 10 reviewtext randomly !

dataset['reviewText'].sample(10)

261644    DO NOT ORDER. Yeah the picture is super cute. ...
650690    They fit as expected because I read all the re...
350368    Needed for a special event.  The price was goo...
4424                                                  Great
628025    These shoes are cute and comfortable, but had ...
85001     This is a cute purse. I love the sizing but th...
11041     I loved this watch . . . at first. In February...
701069    Really cute.  Mine was not so polished when I ...
460133    Basically a very good product except some will...
89558     This ring looks nice, but I ordered a size 10 ...
Name: reviewText, dtype: object

In [6]:
# View the first 10 reviewtext!

dataset['reviewText'].head(10)

0        Great nephew loved!!! Very fast delivery!!!!!
1                       well made boot, fits perfectly
2    Perfect fit. Good quality. (Do not put in dryer.)
3    I bought these for my 2 year old girl and she ...
4    Great backpack.  I wanted to get a backpack th...
5    I use these every day.  They smell great and w...
6                                           Nice pants
7    The first pair of jazz shoes my daughter didn'...
8    Got these shoes for my elderly mother. They fi...
9    I love the Keen Newport Sandal!, they are dura...
Name: reviewText, dtype: object

In [7]:
# In overall we have ratings let's know the counts for ratings 1-5 !

dataset['overall'].unique()

array([5, 4, 3, 2, 1], dtype=int64)

In [8]:
# let's count how many reviews we have for 1 - 5 !

dataset['overall'].value_counts()

3    264000
5    132000
4    132000
2    132000
1    132000
Name: overall, dtype: int64

In [9]:
# Missing values !

dataset.isnull().any(axis = 0)

overall       False
reviewText     True
summary        True
dtype: bool

In [10]:
# Let's drop the columns where we have missing data !

dataset.dropna(inplace = True)

In [11]:
# Again check the missing values !

dataset.isnull().any(axis = 0)

overall       False
reviewText    False
summary       False
dtype: bool

In [12]:
# Let's drop the data which have ratings - 3 !

dataset = dataset[dataset['overall'] != 3]

In [13]:
# Let's check is there rating3 droped aur not !?
dataset['overall'].value_counts()

2    131939
1    131876
4    131849
5    131719
Name: overall, dtype: int64

Create a new columns !

    And divided the overall ratings in two categories !
    0 - negative ratings !
    1 - positive ratings !



In [14]:
dataset['Positivity'] = np.where(dataset['overall'] > 3 , 1 , 0)

In [15]:
# Let's check ratings and there count Positivity Column !

dataset['Positivity'].value_counts()

0    263815
1    263568
Name: Positivity, dtype: int64

In [16]:
dataset['reviewText'].head(10)

0        Great nephew loved!!! Very fast delivery!!!!!
1                       well made boot, fits perfectly
2    Perfect fit. Good quality. (Do not put in dryer.)
3    I bought these for my 2 year old girl and she ...
4    Great backpack.  I wanted to get a backpack th...
5    I use these every day.  They smell great and w...
6                                           Nice pants
7    The first pair of jazz shoes my daughter didn'...
8    Got these shoes for my elderly mother. They fi...
9    I love the Keen Newport Sandal!, they are dura...
Name: reviewText, dtype: object

NLP Data we have to convert our freeform text data into numeric representation !

    To create a ML model all algorithms need data in numeric format. !



In [17]:
# Perform train_test_split

from sklearn.model_selection import train_test_split

In [18]:
# Separate out the features and labels !

features = dataset['reviewText']

labels = dataset['Positivity']

In [19]:
# Splitting the dataset into train and test !

features_train , features_test , labels_train , labels_test = train_test_split(features , labels , test_size = 0.4 ,
                                                                               random_state = 0)

Now we have to convert our NLP text data to a numeric representation using *Vectorization technique !

    We are going to use TfidfVectorizer !



In [20]:
# Import a class !

from sklearn.feature_extraction.text import TfidfVectorizer

In [21]:
# Create a object !

vect = TfidfVectorizer()

In [22]:
# Fitting the daqta !

vect = TfidfVectorizer(min_df = 5).fit(features_train) 

# min_df = 5 means ignore the terms that appear in less then 5 documents !

In [23]:
# What is the count of unique words !

len(vect.get_feature_names())

17313

In [24]:
# Convert NLP test data in numeric representation !

features_train_vectorized = vect.transform(features_train)

We can covert our features_train_vectorized to array using .toarray() function !

    But sometime in this process our system get crashed !

    features_train_vectorised.toarray()



In [25]:
# Create LogisticRegression Model !

from sklearn.linear_model import LogisticRegression

In [26]:
# create object of it !

model = LogisticRegression()

In [27]:
# Now fitt our data !

model.fit(features_train_vectorized , labels_train)

C:\Users\Bad Boy\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [28]:
# Evaluate the Models !
# Model Testing !

prediction = model.predict(vect.transform(features_test))

Let's check our Model is Working Good aur Bad interms of Classification !

In [29]:
#import Confusion Matrix !

from sklearn.metrics import confusion_matrix

In [30]:
confusion_matrix(labels_test , prediction)

array([[95985,  9307],
       [11418, 94244]], dtype=int64)

Check the Probability of our Model !¶

    Probability < 50 = 0 !
    Probability >= 50 = 1 !



In [31]:
# Let's Calculate rthe Accuracy of the Model !

from sklearn.metrics import accuracy_score

In [32]:
accuracy_score(labels_test , prediction)

0.9017558330252093

In [33]:
prediction

array([1, 0, 0, ..., 1, 1, 1])

In [34]:
model.predict_proba(vect.transform(features_test))

array([[0.03106634, 0.96893366],
       [0.52192257, 0.47807743],
       [0.98897343, 0.01102657],
       ...,
       [0.00485688, 0.99514312],
       [0.11682304, 0.88317696],
       [0.38697599, 0.61302401]])

Prediction the Probability / Score of our model is - 90.12% !